package com.chrysalide.transmemo.presentation.theme

import androidx.compose.ui.graphics.Color

internal val primaryLightHighContrast = Color(0xFF2E154A)
internal val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
internal val primaryContainerLightHighContrast = Color(0xFF50376E)
internal val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryLightHighContrast = Color(0xFF002249)
internal val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
internal val secondaryContainerLightHighContrast = Color(0xFF224373)
internal val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryLightHighContrast = Color(0xFF00272C)
internal val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
internal val tertiaryContainerLightHighContrast = Color(0xFF004A53)
internal val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
internal val errorLightHighContrast = Color(0xFFA91313)
internal val onErrorLightHighContrast = Color(0xFFFFFFFF)
internal val errorContainerLightHighContrast = Color(0xFF6B2F44)
internal val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
internal val backgroundLightHighContrast = Color(0xFFFFF7FF)
internal val onBackgroundLightHighContrast = Color(0xFF1D1A20)
internal val surfaceLightHighContrast = Color(0xFFF5FAFB)
internal val onSurfaceLightHighContrast = Color(0xFF000000)
internal val surfaceVariantLightHighContrast = Color(0xFFDBE4E6)
internal val onSurfaceVariantLightHighContrast = Color(0xFF1C2527)
internal val outlineLightHighContrast = Color(0xFF3B4446)
internal val inverseSurfaceLightHighContrast = Color(0xFF2B3133)
internal val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)

internal val primaryDarkHighContrast = Color(0xFFFFF9FC)
internal val onPrimaryDarkHighContrast = Color(0xFF000000)
internal val primaryContainerDarkHighContrast = Color(0xFFDDBEFF)
internal val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
internal val secondaryDarkHighContrast = Color(0xFFFBFAFF)
internal val onSecondaryDarkHighContrast = Color(0xFF000000)
internal val secondaryContainerDarkHighContrast = Color(0xFFB0CCFF)
internal val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
internal val tertiaryDarkHighContrast = Color(0xFFF1FDFF)
internal val onTertiaryDarkHighContrast = Color(0xFF000000)
internal val tertiaryContainerDarkHighContrast = Color(0xFF86D7E5)
internal val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
internal val errorDarkHighContrast = Color(0xFFA91313)
internal val onErrorDarkHighContrast = Color(0xFF000000)
internal val errorContainerDarkHighContrast = Color(0xFFFFB7CC)
internal val onErrorContainerDarkHighContrast = Color(0xFF000000)
internal val backgroundDarkHighContrast = Color(0xFF151218)
internal val onBackgroundDarkHighContrast = Color(0xFFE8E0E8)
internal val surfaceDarkHighContrast = Color(0xFF0E1415)
internal val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
internal val surfaceVariantDarkHighContrast = Color(0xFF3F484A)
internal val onSurfaceVariantDarkHighContrast = Color(0xFFF3FCFE)
internal val outlineDarkHighContrast = Color(0xFFC3CCCE)
internal val inverseSurfaceDarkHighContrast = Color(0xFFDEE3E5)
internal val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
