name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Lint kotlin
      run: ./gradlew lintKotlin

    - name: Unit tests
      run: ./gradlew testDebugUnitTest

    - name: Build with Gradle
      run: ./gradlew assembleRelease -x lint

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: app-release-unsigned.apk
          path: app/build/outputs/apk/release/

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{secrets.FIREBASE_CREDENTIALS}}
          file: app/build/outputs/apk/release/app-release-unsigned.apk
          groups: commu-trans
