name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Lint kotlin
      run: ./gradlew lintKotlin

    - name: Unit tests
      run: ./gradlew testDebugUnitTest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Decode App Distrib Keystore
      run: echo "${{ secrets.APP_DISTRIB_SIGNING_KEYSTORE }}" | base64 -d > ./keystore-app-distrib.jks

    - name: Get app version
      id: appVersion
      uses: ltDino/android-get-version-action@v1.0
      with:
        gradlePath: app/build.gradle.kts

    - name: Calculate new version code
      id: calculateVersionCode
      run: |
         SUM=$((steps.appVersion.outputs.versionCode + github.run_number))
         echo "versionCode=${SUM}" >> $GITHUB_OUTPUT

    - name: Build and sign APK for App Distrib
      run: ./gradlew packageAppDistrib -PversionCode="${{ steps.calculateVersionCode.outputs.versionCode }}"
      env:
        APP_DISTRIB_SIGNING_KEY_ALIAS: ${{ secrets.APP_DISTRIB_SIGNING_KEY_ALIAS }}
        APP_DISTRIB_SIGNING_KEY_PASSWORD: ${{ secrets.APP_DISTRIB_SIGNING_KEY_PASSWORD }}
        APP_DISTRIB_SIGNING_STORE_PASSWORD: ${{ secrets.APP_DISTRIB_SIGNING_STORE_PASSWORD }}

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: TransMemo-appDistrib.apk
        path: app/build/outputs/apk/appDistrib/app-appDistrib.apk


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v4
        with:
          name: TransMemo-appDistrib.apk
          path: apk/

      - name: List files in apk directory
        run: ls -R apk/

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          file: apk/app-appDistrib.apk
          groups: commu-trans
          releaseNotes: ${{ github.event.head_commit.message }}
